### ISSUE TITLE
TypeError: Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by spencekim** [xenova/transformers.js#10]
I am running the flan-t5 model for text2text-generation (e.g. `await pipeline("text2text-generation", "flan-t5-base");`) in a service worker. Seeing this error:

```
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at eval (models.js?a626:289:1)
    at Array.map (<anonymous>)
    at Function.toI64Tensor (models.js?a626:289:1)
    at Function.prepare_inputs (models.js?a626:303:1)
    at Function.forward (models.js?a626:557:1)
    at Function.runBeam (models.js?a626:544:1)
    at Function.generate_single (models.js?a626:366:1)
    at eval (models.js?a626:326:1)
    at Array.map (<anonymous>)
```

**Comment by xenova** [comment]
Could you send the input text that you used?

**Comment by spencekim** [comment]
Here's the exact input:

"Question: Pets?
Files: 13. PETS: Unless otherwise provided in California Civil Code §54. 2, no animal or pet shall be kept on or about the Premises without Landlord's prior written consent, except:. 14. (If checked) NO SMOKING: No smoking of any substance is allowed on the Premises or common areas. 2) Correction on 6A: Late fee of $100/week will apply any rent recieved after 4th of each month. It should be paid by Zelle or bank transfer. 3) One year lease. Tenant will be responsible for the rest of the year rent if they need to move out before the lease expires. 4) Sublease is not allowed and no pets are alloweded at anytime 5) Tenant should open own PGE & Scavenger accounts. Water utility share by headcount. A. R. Form KLA). 20. SIGNS: Tenant authorizes Landlord to place FOR SALE/LEASE signs on the Premises. 21. ASSIGNMENT; SUBLETTING: Tenant shall not sublet all or any part of Premises, or assign or transfer this Agreement or any interest in it, without Landlord's prior written consent.
Answer: "

I believe the issue is the "§" character, as you pointed out in our other thread.

**Comment by xenova** [comment]
Ahh yes - that should be mapped to the UNK_TOKEN. Let me fix that.

**Comment by xenova** [comment]
Silly typo 🙄 Fixed now (https://github.com/xenova/transformers.js/commit/e98915d9d05b0e0936c3f8bc761960824794fb5a).

I will make a new release shortly

**Comment by xenova** [comment]
Version 1.1.1 has just been released (https://www.npmjs.com/package/@xenova/transformers) - can you check if it fixes your problem?

**Comment by spencekim** [comment]
Let me give it a shot right now!

**Comment by spencekim** [comment]
I'm actually getting a different error when initializing the "text2text-generation" pipeline. 

```
Error: File not found. Could not locate "/models/flan-t5-base/seq2seq-lm-with-past/decoder_model_merged.onnx".
    at getModelFile (webpack-internal:///../../node_modules/@xenova/transformers/src/utils.js:152:19)
    at async constructSession (webpack-internal:///../../node_modules/@xenova/transformers/src/models.js:18:18)
    at async Promise.all (index 2)
    at async Function.from_pretrained (webpack-internal:///../../node_modules/@xenova/transformers/src/models.js:150:57)
    at async Promise.all (index 1)
    at async pipeline (webpack-internal:///../../node_modules/@xenova/transformers/src/pipelines.js:452:17)
```

I did not change anything with my path configurations, only upgraded from `1.0.5` to `1.1.1`. Weirdly enough, the embeddings pipeline still works fine and finds the correct models.

**Comment by xenova** [comment]
Oh yes - it should be /google/flan-t5-base

**Comment by spencekim** [comment]
yep, I was able to download the new files for `flan-t5-base` from your huggingface repo:

<img width="273" alt="Screenshot 2023-03-09 at 3 09 34 PM" src="https://user-images.githubusercontent.com/19200359/224181365-b3f1325c-8cc0-4306-b4f9-9c741e8e9750.png">

I set a custom path to my local models (it's not looking for the /google directory, as you can see from my previous comment's stack trace) like so:

```
env.remoteModels = false;
env.localURL = "/models";
```

...and initialize the pipelines like so:

```
...await pipeline("embeddings", "all-MiniLM-L6-v2");
...await pipeline("text2text-generation", "flan-t5-base")
```

Maybe I'm missing something basic, but for some reason the embeddings pipeline works fine, yet the text2text pipeline doesn't work.

**Comment by xenova** [comment]
Try refreshing your browser cache?
Open developer tools (F12) -> Application (at the top) -> Storage -> Clear site data

I think it is caching the request, even if it fails; something I should fix!

**Comment by spencekim** [comment]
Not sure if this is related, but FYI I'm getting this warning with the new release:

```
2023-03-09 21:03:00.501100 [W:onnxruntime:, graph.cc:3490 CleanUnusedInitializersAndNodeArgs] Removing initializer '/decoder/block.7/layer.2/DenseReluDense/act/Constant_2_output_0'. It is not used by any node and should be removed from the model.
```
