### ISSUE TITLE
[Bug] Error fetching models?

### ISSUE THREAD

**Issue by aress31** [xenova/transformers.js#115]
The following code:

```node
import { pipeline } from "@xenova/transformers";

let pipe = await pipeline(
  "text-generation",
  "EleutherAI/gpt-neo"
);
let result = await pipe("Write me a love poem about cheese.", {
  do_sample: false,
  max_new_tokens: 200,
  no_repeat_ngram_size: 3,
  temperature: 0.9,
  repetition_penalty: 2.0,
});

console.log(result);
```

Produces:

```
node .\main.js
file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/utils/hub.js:223
            throw Error(`Could not locate file: "${remoteURL}".`)
                  ^

Error: Could not locate file: "https://huggingface.co/nlptown/EleutherAI/gpt-neo/resolve/main/onnx/model_quantized.onnx".
    at handleError (file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/utils/hub.js:223:19)
    at getModelFile (file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/utils/hub.js:412:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async constructSession (file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/models.js:88:18)
    at async Promise.all (index 1)
    at async AutoModelForSequenceClassification.loadModel [as LOAD_FUNCTION] (file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/models.js:280:16)
    at async AutoModelForSequenceClassification.from_pretrained (file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/models.js:2591:20)
    at async Promise.all (index 1)
    at async pipeline (file:///C:/Users/ares/Github/xxx/test/node_modules/@xenova/transformers/src/pipelines.js:1462:17)
    at async file:///C:/Users/ares/Github/xxx/test/main.js:3:12

Node.js v20.1.0
```

I tried many different `ONNX`-based model from Hugging Face but resulting to the same error.

---

I reckon the issue is with the path the library is looking for, for example with `optimum/gpt2`, the correct path should be:

- https://huggingface.co/optimum/gpt2/blob/main/tokenizer.json

But it seems that the hardcoded path uses `resolve/main` instead of `blob`, see:

- Error: Could not locate file: "https://huggingface.co/optimum/gpt2/resolve/main/tokenizer_config.json".

**Comment by xenova** [comment]
Hi there. This is because the repos you are attempting to use don't contain ONNX weights in a folder called "onnx". Once web-ready models become more popular, hopefully more models will support it.

Fortunately, it's really simple to convert your own models using the conversion script (which uses Optimum behind the scenes). See the [docs](https://huggingface.co/docs/transformers.js/custom_usage) for more info.

To help users get started, I've already converted a lot of models, which can be found by searching on the hub: https://huggingface.co/models?other=transformers.js

In your case, you're trying to load gpt-neo, which I haven't yet converted, but I have converted the 125M version of it: https://huggingface.co/Xenova/gpt-neo-125M

So, you can do:
```js
let pipe = await pipeline(
  "text-generation",
  "Xenova/gpt-neo-125M"
);
```

Hope this helps.

**Comment by xenova** [comment]
Closing the issue for now, but feel free to ask any further questions 👍

**Comment by aress31** [comment]
Thanks for the reply @xenova but I assumed that any `ONNX`-based model would work, meaning any of these models:
- https://huggingface.co/models?library=onnx&sort=downloads

Did I get that wrong?

**Comment by aress31** [comment]
Thanks for taking the time to answer my questions. 😊
