### ISSUE TITLE
[Bug] Module Parse Error in Next.js

### ISSUE THREAD

**Issue by Battjmo** [xenova/transformers.js#183]
**Describe the bug**
When I try to import the library in my next.js app, there's a module import error.

**How to reproduce**
1. Create a next.js app.
2. Import anything from the transformers library in that app.

If I bump the version down to the one from this issue:  https://github.com/xenova/transformers.js/issues/27, the error changes to the one about not having a backend from this issue: https://github.com/xenova/transformers.js/issues/124. I'd rather just stick with the new one of course so I can keep getting updates.

**Expected behavior**
The library loads, works, and does its awesome things.

**Logs/screenshots**
Here's the text of the error:

```
./node_modules/@xenova/transformers/node_modules/onnxruntime-node/bin/napi-v3/darwin/arm64/onnxruntime_binding.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**Environment**
- Transformers.js version: 2.3.1
- Browser (if applicable): Chrome or Firefox
- Operating system (if applicable): MacOS
- Other: next.js 13.4.7

**Additional context**
Thank you so much in advance, apologies if this is something silly I messed up but it seems webpack-y so I thought I'd inquire.

**Comment by xenova** [comment]
Hi there! 👋  I think a user had this problem before, and fixed it as follows: https://github.com/xenova/transformers.js/issues/98#issuecomment-1519378232

I definitely need to make a next.js example app 😄

**Comment by Battjmo** [comment]
@xenova thank you, yes, this is perfect! Can't believe I missed that example. 

I think having my transformer functionality in an API route is probably the way to go anyway, which I suspect will fix this problem too.

Rock on.

**Comment by xenova** [comment]
Happy to help! 🤗 Good luck! 🚀

**Comment by Battjmo** [comment]
Oops, I think I jumped the gun. Now I get this (serverside, which should be okay from a node runtime standpoint?):

'Cannot find module 'onnxruntime-node''

Thanks again, much love.

**Comment by xenova** [comment]
Right, [onnxruntime-node](https://www.npmjs.com/package/onnxruntime-node) is listed as an optional dependency in the package.json:

https://github.com/xenova/transformers.js/blob/aceab9bf3d1be9dadf6601b8f775e519376258e3/package.json#L45C4-L45C4

So, you'll just need to install it separately: 
```
npm i onnxruntime-node
```

Just one note: I've only tested v1.14.x, but 1.15.1 is now out, so, you can try the more-recent version if you want, but I'd recommend just staying on 1.14 until they have their WebGPU problems sorted out (which is the main reason why I haven't updated yet)

**Comment by Battjmo** [comment]
I do have it installed separately, sad to say. Will keep fiddling with it.

I fear next.js may have gotten too cute in 13.

**Comment by Battjmo** [comment]
Stack trace: 

```- error Error: Cannot find module 'onnxruntime-node'
    at webpackMissingModule (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/backends/onnx.js:7:50)
    at eval (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/backends/onnx.js:7:141)
    at (sc_server)/./node_modules/@xenova/transformers/src/backends/onnx.js (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:118:1)
    at __webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/env.js:8:75)
    at (sc_server)/./node_modules/@xenova/transformers/src/env.js (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:140:1)
    at __webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/utils/hub.js:10:65)
    at (sc_server)/./node_modules/@xenova/transformers/src/utils/hub.js (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:239:1)
    at __webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/tokenizers.js:28:71)
    at (sc_server)/./node_modules/@xenova/transformers/src/tokenizers.js (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:184:1)
    at __webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/pipelines.js:22:72)
    at (sc_server)/./node_modules/@xenova/transformers/src/pipelines.js (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:162:1)
    at __webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/@xenova/transformers/src/transformers.js:183:71)
    at (sc_server)/./node_modules/@xenova/transformers/src/transformers.js (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:195:1)
    at __webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/embeddings/embeddings.ts:5:78)
    at (sc_server)/./src/app/embeddings/embeddings.ts (/Users/thelampshade/valquery/.next/server/_sc_server_src_app_embeddings_embeddings_ts.js:107:1)
    at Function.__webpack_require__ (/Users/thelampshade/valquery/.next/server/webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateEmbeddings (webpack-internal:///(sc_server)/./src/app/embeddings/route.ts:25:22)
    at async POST (webpack-internal:///(sc_server)/./src/app/embeddings/route.ts:42:21)
    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:249:37) {
  code: '```

**Comment by xenova** [comment]
Well, the above error message says like you're using webpack? And in your next.js' webpack config, you're ignoring onnxruntime-node, right? So, I see why you're getting that error.

Is there a reason you're using webpack on the server-side? Looks like webpack isn't having too much fun with the .node files.

**Comment by Battjmo** [comment]
I'm not using webpack that I know of. Only mention of it in the app is that `next.config.js` change from the earlier comment.

**Comment by xenova** [comment]
According to https://nextjs.org/docs/messages/webpack5
> Next.js has adopted webpack 5 as the default for compilation.

**Comment by Battjmo** [comment]
Ah, so I'm using it whether I want to or not 🤪 . I'll fiddle with bringing that loader in. Thanks!

**Comment by Battjmo** [comment]
Alright, got this fixed. Turns out everything in the app router winds up in the client bundle whether you need it there or not? So I went back to the old reliable pages folder and made an API route, use your library there, and it works!

Thanks again 👍

**Comment by derbuihan** [comment]
@Battjmo 
I am also trying to use this library with Next.js. I have never set up webpack, so I have not been able to resolve an error similar to this Issue. If you are having success, I would like you to publish that project.
