### ISSUE TITLE
[Bug] can not run the react-translator example

### ISSUE THREAD

**Issue by yujiaao** [xenova/transformers.js#214]
**pnpm  run dev**
*under chrome 117.0.5897.3 open `http://localhost:5173/`*

in the console show warning and errors:

 
Aborted(LinkError: WebAssembly.instantiate(): Import #41 module="a" function="P" error: function import requires a callable)

```
Uncaught (in promise) Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #41 module="a" function="P" error: function import requires a callable). Build with -sASSERTIONS for more info.
    at backend-impl.js:87:11
    at async d.create (inference-session-impl.js:169:15)
    at async constructSession (models.js:91:16)
    at async Promise.all (:5173/index 1)
    at async AutoModelForSeq2SeqLM.seq2seqLoadModel [as LOAD_FUNCTION] (models.js:294:16)
    at async AutoModelForSeq2SeqLM.from_pretrained (models.js:2591:20)
    at async Promise.all (:5173/index 1)
    at async pipeline (pipelines.js:1462:17)
    at async worker.js?type=module&worker_file:28:22
(匿名) @ backend-impl.js:87
```

**Expected behavior**
show translate result

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

<img width="662" alt="image" src="https://github.com/xenova/transformers.js/assets/2154284/cc9fcdae-4f87-4753-828a-21e414bc35cb">

**Environment**
- Transformers.js version:
    "@xenova/transformers": "^2.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"

- Browser (if applicable):  chrome 117.0.5897.3, Edge do the same
- Operating system (if applicable): MacOS

**Additional context**
*Add any other context about the problem here.*

**Comment by xenova** [comment]
This error usually occurs when the version of onnxruntime does not match the WASM files. Which version of transformers.js are you exactly using?

**Comment by yujiaao** [comment]
> 


onnxruntime and transformers  related packages:

```
  registry.npmmirror.com/@xenova/transformers@2.0.0:
    resolution: {integrity: sha512-dTLzljbmPa9ewy43OpLzm8KQPAzj0ssEg55e9NKuTLmG7AolaT49gXiOc1IISc6aze4DNv+rUdYwMLPBQMN2SA==, registry: https://registry.npm.taobao.org/, tarball: https://registry.npmmirror.com/@xenova/transformers/-/transformers-2.0.0.tgz}
    name: '@xenova/transformers'
    version: 2.0.0
    dependencies:
      onnxruntime-web: registry.npmmirror.com/onnxruntime-web@1.15.1
      sharp: registry.npmmirror.com/sharp@0.32.4
    optionalDependencies:
      onnxruntime-node: registry.npmmirror.com/onnxruntime-node@1.15.1
    dev: false


registry.npmmirror.com/onnxruntime-common@1.15.1:
    resolution: {integrity: sha512-Y89eJ8QmaRsPZPWLaX7mfqhj63ny47rSkQe80hIo+lvBQdrdXYR9VO362xvZulk9DFkCnXmGidprvgJ07bKsIQ==, registry: https://registry.npm.taobao.org/, tarball: https://registry.npmmirror.com/onnxruntime-common/-/onnxruntime-common-1.15.1.tgz}
    name: onnxruntime-common
    version: 1.15.1
    dev: false

  registry.npmmirror.com/onnxruntime-node@1.15.1:
    resolution: {integrity: sha512-wzhVELulmrvNoMZw0/HfV+9iwgHX+kPS82nxodZ37WCXmbeo1jp3thamTsNg8MGhxvv4GmEzRum5mo40oqIsqw==, registry: https://registry.npm.taobao.org/, tarball: https://registry.npmmirror.com/onnxruntime-node/-/onnxruntime-node-1.15.1.tgz}
    name: onnxruntime-node
    version: 1.15.1
    os: [win32, darwin, linux]
    requiresBuild: true
    dependencies:
      onnxruntime-common: registry.npmmirror.com/onnxruntime-common@1.15.1
    dev: false
    optional: true

  registry.npmmirror.com/onnxruntime-web@1.15.1:
    resolution: {integrity: sha512-Ky4AXFLFyiGRu5KQJdDcbhdNcO0f2ND/8IPmTEwcKKIHpCwH6/Q9UoMpcoFz78lxGvnmmy+FFgA/Bs1HjdM6LA==, registry: https://registry.npm.taobao.org/, tarball: https://registry.npmmirror.com/onnxruntime-web/-/onnxruntime-web-1.15.1.tgz}
    name: onnxruntime-web
    version: 1.15.1
    dependencies:
      flatbuffers: registry.npmmirror.com/flatbuffers@1.12.0
      guid-typescript: registry.npmmirror.com/guid-typescript@1.0.9
      long: registry.npmmirror.com/long@4.0.0
      onnx-proto: registry.npmmirror.com/onnx-proto@4.0.4
      onnxruntime-common: registry.npmmirror.com/onnxruntime-common@1.15.1
      platform: registry.npmmirror.com/platform@1.3.6
    dev: false

```

**Comment by xenova** [comment]
Yes, there is indeed a mismatch. V2.0.0 should use ORT 1.14.

To fix this, install transformers.js version 2.4.2

**Comment by xenova** [comment]
Closing due the positive reactions to the previous messages 👍  Feel free to reopen or ask any further questions.
