### ISSUE TITLE
[Bug] Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by datduyng** [xenova/transformers.js#318]
**Describe the bug**
*A clear and concise description of what the bug is.*

```
InitializersAndNodeArgs] Removing initializer '/decoder/decoder/layers.1/self_attn_layer_norm/Constant_output_0'. It is not used by any node and should be removed from the model.
- error Error [TypeError]: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at file:///Users/datduyn/Documents/mygithub.com/embedcloud-server-interference/vercel_serverless/node_modules/.pnpm/@xenova+transformers@2.6.0/node_modules/@xenova/transformers/src/models.js:252:47
    at Array.map (<anonymous>)
    at toI64Tensor (file:///Users/datduyn/Documents/mygithub.com/embedcloud-server-interference/vercel_serverless/node_modules/.pnpm/@xenova+transformers@2.6.0/node_modules/@xenova/transformers/src/models.js:252:38)
    at Function.seq2seqRunBeam [as _runBeam] (file:///Users/datduyn/Documents/mygithub.com/embedcloud-server-interference/vercel_serverless/node_modules/.pnpm/@xenova+transformers@2.6.0/node_modules/@xenova/transformers/src/models.js:404:28)
    at Function.runBeam (file:///Users/datduyn/Documents/mygithub.com/embedcloud-server-interference/vercel_serverless/node_modules/.pnpm/@xenova+transformers@2.6.0/node_modules/@xenova/transformers/src/models.js:1260:27)
    at Function.generate (file:///Users/datduyn/Documents/mygithub.com/embedcloud-server-interference/vercel_serverless/node_modules/.pnpm/@xenova+transformers@2.6.0/node_modules/@xenova/transformers/src/models.js:980:41)
    at Function._call (file:///Users/datduyn/Documents/mygithub.com/embedcloud-server-interference/vercel_serverless/node_modules/.pnpm/@xenova+transformers@2.6.0/node_modules/@xenova/transformers/src/pipelines.js:1361:43)
    at async handler (webpack-internal:///(api)/./src/lib/base-model-api-handler.ts:32:28) {
  digest: undefined
}
```

**How to reproduce**

```
let url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/cats.jpg';
let captioner = await pipeline('image-to-text', 'Xenova/donut-base-finetuned-cord-v2');
let output = await captioner(url);
// [{ generated_text: 'a cat laying on a couch with another cat' }]
```

Running on Nextjs

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: 2.6.0
- MacOS M2

Seems to be related to #10

**Comment by kungfooman** [comment]
Debugging context:

![image](https://github.com/xenova/transformers.js/assets/5236548/937fe5fa-8c72-4a28-ba71-15f673e91d3a)

**Comment by xenova** [comment]
Hi there 👋 Thanks for the report. It looks like this is due to `decoder_start_token_id` being set to null in [config.json](https://huggingface.co/naver-clova-ix/donut-base-finetuned-cord-v2/blob/main/config.json#L23). Also, it should be noted that donut-swin models are technically [not yet supported by transformers.js](https://github.com/xenova/transformers.js#models), which is why there are issues (I haven't tested them before for correctness). I've only converted the models so far (because I intended to add support for them soon).

**Comment by xenova** [comment]
Okay I've got the "Document Parsing" demo from the [docs](https://huggingface.co/docs/transformers/model_doc/donut) working in transformers.js (see [PR](https://github.com/xenova/transformers.js/pull/320)).

@datduyng From your code example, it's a little difficult to understand what exactly you are trying to do. Is it just OCR that you're looking to do? The donut models I have converted are specifically for document understanding (but you are passing it an image of a cat? 🐱)

I do plan to add the document question answering pipeline though.

**Comment by datduyng** [comment]
Thanks for the quick help @xenova, Yeah, I want to do document parsing. The cat was just a sanity check image 😄
