### ISSUE TITLE
[Question] Headers not defined

### ISSUE THREAD

**Issue by trilloc** [xenova/transformers.js#365]
Hi friends!

Neither headers nor fetch seems to be getting resolved.. trying to run this on a nodejs application...

file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:201
        return fetch(urlOrPath, { headers });
               ^

TypeError: fetch is not a function
    at getFile (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:201:16)
    at getModelFile (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:468:30)
    at async getModelJSON (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/tokenizers.js:52:16)
    at async Function.from_pretrained (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/tokenizers.js:3826:48)
    at async Promise.all (index 0)
    at async loadItems (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/pipelines.js:2193:5)
    at async pipeline (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/pipelines.js:2139:19)
    at async Server.<anonymous> (/home/rajesh/code/ai/js/invoice/inv.js:65:24)

-------

Unable to load from local path "/home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/models/Xenova/distilbert-base-uncased-finetuned-sst-2-english/tokenizer.json": "ReferenceError: Headers is not defined"
Unable to load from local path "/home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/models/Xenova/distilbert-base-uncased-finetuned-sst-2-english/tokenizer_config.json": "ReferenceError: Headers is not defined"
Unable to load from local path "/home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/models/Xenova/distilbert-base-uncased-finetuned-sst-2-english/config.json": "ReferenceError: Headers is not defined"
file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:188
        const headers = new Headers();
                        ^

ReferenceError: Headers is not defined
    at getFile (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:188:25)
    at getModelFile (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:468:30)
    at async getModelJSON (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/tokenizers.js:52:16)
    at async Function.from_pretrained (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/tokenizers.js:3826:48)
    at async Promise.all (index 0)
    at async loadItems (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/pipelines.js:2193:5)
    at async pipeline (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/pipelines.js:2139:19)

**Comment by trilloc** [comment]
also getReader...

file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:572
    const reader = response.body.getReader();
                                 ^

TypeError: response.body.getReader is not a function
    at readResponse (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:572:34)
    at getModelFile (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:493:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getModelJSON (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/utils/hub.js:542:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/tokenizers.js:52:16)
    at async Function.from_pretrained (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/tokenizers.js:3826:48)
    at async Promise.all (index 0)
    at async loadItems (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/pipelines.js:2193:5)
    at async pipeline (file:///home/rajesh/code/ai/js/invoice/node_modules/@xenova/transformers/src/pipelines.js:2139:19)

**Comment by gramsaroli** [comment]
@trilloc which version of node are you used ?

**Comment by rygrams** [comment]
@trilloc what version of node are you using ?

**Comment by trilloc** [comment]
Hi friends

The problem occurs with node 16 and node 18..

**Comment by xenova** [comment]
Hi there 👋 As mentioned in other threads, due to node 16 reaching EOL, we will not be adding support for it in future. Could you share which exact version of node 18 you are using - as this should not be occurring with v18.
