### ISSUE TITLE
[Question] onnxruntime_binding.node issue on mac electron app

### ISSUE THREAD

**Issue by samlhuillier** [xenova/transformers.js#372]
Hi,
I'm getting this error on an intel macbook running an electron forge app:
```
(node:63267) UnhandledPromiseRejectionWarning: Error: Cannot find module '../bin/napi-v3/darwin/x64/onnxruntime_binding.node'
Require stack:
- /Users/sam/Desktop/electron-forge-react-typescript-tailwind/.webpack/main/index.js
- /Users/sam/Desktop/electron-forge-react-typescript-tailwind/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/binding.js (/Users/sam/Desktop/electron-forge-react-typescript-tailwind/.webpack/main/index.js:229:1)
    at __webpack_require__ (/Users/sam/Desktop/electron-forge-react-typescript-tailwind/.webpack/main/index.js:83093:42)
    at ./node_modules/@xenova/transformers/node_modules/onnxruntime-node/dist/backend.js (/Users/sam/Desktop/electron-forge-react-typescript-tailwind/.webpack/main/index.js:153:19)
```
I check the path ```../bin/napi-v3/darwin/x64/onnxruntime_binding.node``` and it does exist in node_modules. So I'm not sure what's going on/whether this is a bug.

**Comment by xenova** [comment]
Hi there 👋 Could you try our electron sample template (https://github.com/xenova/transformers.js/tree/main/examples/electron) to see if that works?

**Comment by samlhuillier** [comment]
Yes that does work. I suspect it may be an issue with webpack. Do you having any suggestions for setting up transformers.js in an electron webpack app?

**Comment by samlhuillier** [comment]
Seems to be a strange issue with the electron boilerplate & webpack. I've switched over to using vite and it's working fine :)
