### ISSUE TITLE
Unable to convert my model to ONNX

### ISSUE THREAD

**Issue by jason-trinidad** [xenova/transformers.js#419]
**Describe the bug**
*A clear and concise description of what the bug is.*

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: 2.8.0
- Browser (if applicable):
- Operating system (if applicable): macOS 13.4.1

**Comment by xenova** [comment]
Could you try first convert the model to be compatible with pytorch before running the conversion script? Admittedly, I haven't tried converting directly to ONNX from a tensorflow model.

**Comment by jason-trinidad** [comment]
Got a chance to try this - I re-trained the model using PyTorch and re-ran the script. Looks like the ONNX export succeeded this time! Thanks for the tip.

I did run into an error with quantization:

"""
Quantizing:   0%|                                                                 | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Jason/Documents/Projects/ai_scheduler/convert_to_onnx.py", line 396, in <module>
    main()
  File "/Users/Jason/Documents/Projects/ai_scheduler/convert_to_onnx.py", line 372, in main
    quantize([
  File "/Users/Jason/Documents/Projects/ai_scheduler/convert_to_onnx.py", line 230, in quantize
    quantize_dynamic(
TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'
"""

And another error when I tried to load my model from Huggingface using transformers.js'. 

Via `AutoModel.from_pretrained('[HF location]', {'quantized': false})`:

"""
Error: Could not locate file: "https://huggingface.co/jason-trinidad/t5-small-ft-120123-torch/resolve/main/onnx/decoder_model_merged.onnx".
    at handleError (hub.js:240:11)
    at getModelFile (hub.js:473:24)
    at async constructSession (models.js:119:18)
    at async Promise.all (:5173/index 2)
    at async T5Model.from_pretrained (models.js:750:20)
    at async AutoModel.from_pretrained (models.js:3960:20)
    at async loadModel (List.jsx:41:21)
"""

Does the quantization output some kind of merged file that `T5_model.from_pretrained()` looks for? Quantization is not crucial for me at the moment so if this is the issue I'd be happy to use a workaround!

**Comment by xenova** [comment]
This looks like a dependency version issue. Can you try with [this list](https://github.com/xenova/transformers.js/blob/main/scripts/requirements.txt) of requirements? The combination should work for t5 models.

**Comment by jason-trinidad** [comment]
Hi sorry for the delay. Tried this on a new env with the requirements you linked to, I got the same error. It's looking for `decoder_model_merged.onnx`. Any ideas?

**Comment by xenova** [comment]
If you could provide the ID of the model you are looking to convert, I could try it on my side.

**Comment by jason-trinidad** [comment]
Thanks, I uploaded it to "jason-trinidad/t5-ft-to-convert" on HF. I was using your conversion script.

**Comment by xenova** [comment]
Thanks! I did the conversion myself and I didn't run into any issues. I opened a [PR](https://huggingface.co/jason-trinidad/t5-ft-to-convert/tree/refs%2Fpr%2F1) to your repo and ran it with the following code:

```js
import { pipeline } from '@xenova/transformers';

const pipe = await pipeline('text2text-generation', 'jason-trinidad/t5-ft-to-convert', {
    // quantized: false, Uncomment this line to use the unquantized version
    revision: 'refs%2Fpr%2F1',
});
const result = await pipe('Translate to German: Hello', {
    max_new_tokens: 50,
});
console.log(result);
// [{ generated_text: 'Hallo' }]
```

**Comment by shizheng-rlfresh** [comment]
Hi! I had similar issue and I used the conversion script + requirement dependency. In addition, I always got an error of "unsupported model IR version: 9, max supported IR version 8. My ID is [shi-zheng-qxhs/gpt2_oasst2_curated](https://huggingface.co/shi-zheng-qxhs/gpt2_oasst2_curated)

**Comment by SmarMykel** [comment]
@shizheng-rlfresh Were you able to fix the "unsupported model IR version: 9, max supported IR version 8"

**Comment by shizheng-rlfresh** [comment]
@SmarMykel have you tried the recommended [script](https://github.com/xenova/transformers.js/tree/main/scripts)? try use a venv and run the script...see if that works 😄 
```python
python -m venv .venv
# activate .venv and install required packages
source .venv/bin/activate
pip install -r requirements.txt
# run the conversion script - <modelid>
python -m scripts.convert --quantize --model_id <modelid>
```

**Comment by SmarMykel** [comment]
Its working thank you!!! @shizheng-rlfresh
