### ISSUE TITLE
The "path" argument must be of type string or an instance of URL. Received undefined

### ISSUE THREAD

**Issue by logancyang** [xenova/transformers.js#526]
### System Info

transformers.js version: 2.14.0
MacOS Sonoma 14.2.1
NodeJS: v19.8.1
React: v18.2.0

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [X] Desktop app (e.g., Electron)
- [X] Other (e.g., VSCode extension)

### Description

Hi I'm trying to follow this [instruction at LangchainJS](https://js.langchain.com/docs/integrations/text_embedding/transformers) to use the huggingface transformers embeddings in my Obsidian plugin [copilot](https://github.com/logancyang/obsidian-copilot), but am seeing an error regarding this package, not sure how to fix, any help is greatly appreciated! Let me know if anything else is needed to debug this.

## Issue
```js
// node_modules/@xenova/transformers/src/env.js
var import_meta = {};
var { env: onnx_env } = ONNX;
var VERSION2 = "2.14.0";
var WEB_CACHE_AVAILABLE = typeof self !== "undefined" && "caches" in self;
var FS_AVAILABLE = !isEmpty(import_fs.default);
var PATH_AVAILABLE = !isEmpty(import_path.default);
var RUNNING_LOCALLY = FS_AVAILABLE && PATH_AVAILABLE;
var __dirname = RUNNING_LOCALLY ? import_path.default.dirname(import_path.default.dirname(import_url.default.fileURLToPath(import_meta.url))) : "./";

Error:
Plugin failure: copilot TypeError: The "path" argument must be of type string or an instance of URL. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at Object.fileURLToPath (node:internal/url:1491:11)
    at anonymous (plugin:copilot:89293:110)
    at e.<anonymous> (app.js:1:2026677)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

## Additional info
Obsidian uses esbuild and my config is:

```js
import builtins from "builtin-modules";
import esbuild from "esbuild";
import svgPlugin from "esbuild-plugin-svg";
import process from "process";
import wasmPlugin from "./wasmPlugin.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [svgPlugin(), wasmPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
```

**Comment by hiepxanh** [comment]
console log your variable: var __dirname = RUNNING_LOCALLY ? import_path.default.dirname(import_path.default.dirname(import_url.default.fileURLToPath(import_meta.url))) : "./";

this __dirname not return string or URL instance, look like it return undefined

`Plugin failure: copilot TypeError: The "path" argument must be of type string or an instance of URL. Received undefined`

**Comment by logancyang** [comment]
@hiepxanh the stacktrace I posted shows `Object.fileURLToPath` got undefined as argument, so `import_meta.url` is undefined. A couple of lines above there's `import_meta = {}` so there's URL for sure. Not sure what to make of this.

**Comment by hiepxanh** [comment]
do you use ESM?

**Comment by logancyang** [comment]
> do you use ESM?

Just confirmed with the Obsidian community, ESM is not an option right now, all Obsidian plugin must be CJS. I wonder what I can do here 🫠

**Comment by hiepxanh** [comment]
@logancyang  you cannot do anything, I have to refactor my code to ESM and decided to give up and use API haha
