### ISSUE TITLE
How to convert BAAI/bge-m3 for Transformers.js?

### ISSUE THREAD

**Issue by devfacet** [xenova/transformers.js#553]
### Question

I tried to convert https://huggingface.co/BAAI/bge-m3 to ONNX using the instructions at https://github.com/xenova/transformers.js?tab=readme-ov-file#convert-your-models-to-onnx but I'm getting errors.

```shell
$ python -m scripts.convert --model_id BAAI/bge-m3

Framework not specified. Using pt to export to ONNX.
Automatic task detection to feature-extraction (possible synonyms are: default, mask-generation, sentence-similarity).
Using the export variant default. Available variants are:
	- default: The default ONNX variant.
Using framework PyTorch: 2.0.1
Overriding 1 configuration item(s)
	- use_cache -> False
================ Diagnostic Run torch.onnx.export version 2.0.1 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Saving external data to one file...
Post-processing the exported models...
Deduplicating shared (tied) weights...
Validating ONNX model models/BAAI/bge-m3/model.onnx...
	-[✓] ONNX model output names match reference model (last_hidden_state)
	- Validating ONNX Model output "last_hidden_state":
		-[✓] (2, 16, 1024) matches (2, 16, 1024)
		-[✓] all values close (atol: 0.0001)
The ONNX export succeeded and the exported model was saved at: models/BAAI/bge-m3
```

```shell
cat test.js
```
```js
import { pipeline } from './src/transformers.js'

const extractor = await pipeline('feature-extraction', 'BAAI/bge-m3', {
  quantized: false,
  cache_dir: './models',
  local_files_only: true,
})

const embedding = await extractor('hello there', { pooling: 'mean', normalize: true })
console.log(JSON.stringify(Array.from(embedding.data), null, 2))
```

```shell
2024-01-31 20:35:16.548 node[64946:11650151] 2024-01-31 20:35:16.548343 [E:onnxruntime:, inference_session.cc:1532 operator()] Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/optimizer/initializer.cc:31 onnxruntime::Initializer::Initializer(const onnx::TensorProto &, const onnxruntime::Path &) !model_path.IsEmpty() was false. model_path must not be empty. Ensure that a path is provided when the model is created or loaded.
Error: Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/optimizer/initializer.cc:31 onnxruntime::Initializer::Initializer(const onnx::TensorProto &, const onnxruntime::Path &) !model_path.IsEmpty() was false. model_path must not be empty. Ensure that a path is provided when the model is created or loaded.

    at new OnnxruntimeSessionHandler (***/transformers.js/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at ***/transformers.js/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback.
Aborted(Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm')
failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.)
***/transformers.js/node_modules/onnxruntime-web/dist/ort-web.node.js:6
...
...
...
Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
    at ***/transformers.js/node_modules/onnxruntime-common/dist/ort-common.node.js:6:11822
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m.create (***/transformers.js/node_modules/onnxruntime-common/dist/ort-common.node.js:6:11480)
    at async constructSession (file://***/transformers.js/src/models.js:140:16)
    at async Promise.all (index 1)
    at async XLMRobertaModel.from_pretrained (file://***/transformers.js/src/models.js:793:20)
    at async AutoModel.from_pretrained (file://***/transformers.js/src/models.js:5166:20)
    at async Promise.all (index 1)
    at async loadItems (file://***/transformers.js/src/pipelines.js:3116:5)
    at async pipeline (file://***/transformers.js/src/pipelines.js:3056:21)

Node.js v20.9.0
```

**Comment by xenova** [comment]
I believe the reason for this is that onnxruntime-web v1.14.0 doesn't support the external data format - which is required to load models > 2GB in size (like this one). v1.17.0 (main) should have added this (see [here](https://github.com/microsoft/onnxruntime/pull/19087)), however it has not been released yet.

**Comment by devfacet** [comment]
Seems like they just released v1.17.0

https://www.npmjs.com/package/onnxruntime-web
https://www.npmjs.com/package/onnxruntime-node

I tried:

```shell
$ git diff package.json

diff --git a/package.json b/package.json
index da3b5f2..379abd6 100644
--- a/package.json
+++ b/package.json
@@ -38,12 +38,12 @@
   },
   "homepage": "https://github.com/xenova/transformers.js#readme",
   "dependencies": {
-    "onnxruntime-web": "1.14.0",
+    "onnxruntime-web": "1.17.0",
     "sharp": "^0.32.0",
     "@huggingface/jinja": "^0.1.0"
   },
   "optionalDependencies": {
-    "onnxruntime-node": "1.14.0"
+    "onnxruntime-node": "1.17.0"
   },
   "devDependencies": {
     "@types/jest": "^29.5.1",
```

Still getting errors:

```shell
$ node test.js

Error: Invalid argument: sessionOptions.executionProviders[1] is unsupported: 'wasm'.
    at new OnnxruntimeSessionHandler (***/transformers.js/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at ***/transformers.js/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback.
env.wasm.numThreads is set to 4, however, currently onnxruntime-web does not support multi-threads in Node.js. Please consider using onnxruntime-node for performance critical scenarios.
failed to asynchronously prepare wasm: Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm'
Aborted(Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm')
***/transformers.js/node_modules/onnxruntime-common/dist/cjs/backend-impl.js:91
    throw new Error(`no available backend found. ERR: ${errors.map(e => `[${e.name}] ${e.err}`).join(', ')}`);
          ^

Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '***/transformers.js/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
    at resolveBackend (***/transformers.js/node_modules/onnxruntime-common/dist/cjs/backend-impl.js:91:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InferenceSession.create (***/transformers.js/node_modules/onnxruntime-common/dist/cjs/inference-session-impl.js:185:25)
    at async constructSession (file://***/transformers.js/src/models.js:140:16)
    at async Promise.all (index 1)
    at async XLMRobertaModel.from_pretrained (file://***/transformers.js/src/models.js:793:20)
    at async AutoModel.from_pretrained (file://***/transformers.js/src/models.js:5166:20)
    at async Promise.all (index 1)
    at async loadItems (file://***/transformers.js/src/pipelines.js:3116:5)
    at async pipeline (file://***/transformers.js/src/pipelines.js:3056:21)

Node.js v20.9.0
```

**Comment by xenova** [comment]
> Seems like they just released v1.17.0

It requires additional parameters to the `InferenceSession.create` function iirc, which we haven't added support for yet. Perhaps @guschmue can provide more info on this.

**Comment by guschmue** [comment]
Yes, ort-1.17.0 should be out and it has some fixes for large models. 
There are some changes to our tensor class that require some change to transformers.js ...
I wanted to take a few days and send a PR for this together with some changes for webgpu ... mid next week I hope.

**Comment by xenova** [comment]
For testing purposes, I've uploaded a transformers.js-compatible version at https://huggingface.co/Xenova/bge-m3. Although, do note that you cannot use the unquantized version yet.

**Comment by devfacet** [comment]
@xenova: qq: Why/what is `{ pooling: 'cls', ... }`?

**Comment by xenova** [comment]
The default value for pooling is CLS in the original repo: https://github.com/FlagOpen/FlagEmbedding/blob/764a7239d576d7975ef95cee8d74f571da050eea/FlagEmbedding/bge_m3.py#L30

**Comment by xenova** [comment]
Closing since https://huggingface.co/Xenova/bge-m3 has been converted (the remaining issue has to do with loading models >2GB, and is not specific to this issue).

See the model card for example usage.

**Comment by guschmue** [comment]
I tested this with ort-1.17.0 - quantized version is fine, correct results @ 1352ms.
Also tested a fp16 flavor with webgpu @ 52ms.
I have local changes to transformers.js to enable 1.17 - wanted to send a PR but got stuck on something else, should be able to send it next week.

**Comment by devfacet** [comment]
@guschmue : Could you point out the PR here once it's sent? I want to give it a quick shot. Looking forward to trying this model on Raspberry Pi5.

Thank you for your hard work. 🙏
