### ISSUE TITLE
Generating bundle.js error “SyntaxError: Unexpected token”

### ISSUE THREAD

**Issue by ArturLevchuk** [xenova/transformers.js#590]
### System Info

    "@xenova/transformers": "^2.15.0",
    "browserify": "^17.0.0",
    "@babel/core": "^7.23.5",
    "@babel/preset-env": "^7.23.5",
    "babel-loader": "^9.1.3",
    "babelify": "^10.0.0",
    "webpack": "^5.89.0",

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Hi! I have this error when i’m trying to generate bundle.js with browserify. This error happens just by importing package like `import { pipeline, env } from "@xenova/transformers";` 
I also tried to build it with webpack and it builts without errors and works for browser, but when i'm using bundle for mobile webview (flutter_inappwebview 6.0.0) error shows again `[AndroidInAppWebViewController] (android) WebView ID 0 calling "onConsoleMessage" using {messageLevel: 3, message: Uncaught SyntaxError: Unexpected token '='}`

### Reproduction

build with browserify :
`browserify ./src/index.js -o ./dist/bundle.js -t [ babelify --global --presets [@babel/preset-env] --extensions \".js\",\".jsx\"  ]`

.babelrc :
```
{
  "presets": [["@babel/preset-env", {
    "targets": "> 0.25%, not dead",
    "useBuiltIns": "usage",
    "corejs": 3
  }]]
}
```

error:  

```
SyntaxError: Unexpected token (45:119) while parsing C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\@xenova\transformers\src\env.js while parsing file: C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\@xenova\transformers\src\env.js
    at DestroyableTransform.end [as _flush] (C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\insert-module-globals\index.js:114:21)
    at DestroyableTransform.prefinish (C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\insert-module-globals\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:518:28)
    at prefinish (C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\insert-module-globals\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\insert-module-globals\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\insert-module-globals\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (C:\Users\Artur\Documents\data_source_analyzer\assets\client_data_source_analyzer\node_modules\insert-module-globals\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at BabelifyStream.onend (node:internal/streams/readable:946:10)
    at Object.onceWrapper (node:events:632:28)
    at BabelifyStream.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)```
```

**Comment by kungfooman** [comment]
I read Flutter is using QuickJS under the hood - as much as I admire QuickJS, I have a feeling that is the crux.

**Comment by ArturLevchuk** [comment]
> Hi there 👋 Which version of node.js are you using? This seems like an issue with an outdated version (< 18): `Uncaught SyntaxError: Unexpected token '='`

node version is v20.11.0. I find out that vite can help me and tried it. this error dissapered. but i caught new one like: `[AndroidInAppWebViewController] (android) WebView ID 182392382185519613868210114045117412639 calling "onConsoleMessage" using {messageLevel: 1, message: TypeError: env$1.remotePathTemplate.replaceAll is not a function}`

**Comment by xenova** [comment]
@ArturLevchuk `String.replaceAll` should be supported by all modern browsers and engines (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)), so this seems to be a version issue with flutter. You might need to introduce some global polyfills to fix this if you are unable to update the version.

**Comment by ArturLevchuk** [comment]
> @ArturLevchuk `String.replaceAll` should be supported by all modern browsers and engines (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll)), so this seems to be a version issue with flutter. You might need to introduce some global polyfills to fix this if you are unable to update the version.

Yeah you are right. After adding babel/preset-env configuration to vite it finaly works. Thanks for you help!
