### ISSUE TITLE
Error: Module did not self-register: '/node_modules/onnxruntime-node/bin/napi-v3/linux/x64/onnxruntime_binding.node'

### ISSUE THREAD

**Issue by rajeshlatlong** [xenova/transformers.js#651]
### System Info

@xenova/transformers": "^2.15.0", node js, Ubuntu 20.04 LTS

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Facing similar kind of issue for me too when using transformer js as
```
const TransformersApi = Function('return import("@xenova/transformers")')();
 const { CLIPVisionModelWithProjection, RawImage, AutoProcessor } = await TransformersApi;
```
Its working fine when request comes to my application for the first time. I am executing this code as a worker in node js application. But when next request comes to my application its giving error for me as
`Error: Module did not self-register: '/server/node_modules/onnxruntime-node/bin/napi-v3/linux/x64/onnxruntime_binding.node'. at Module._extensions..node (/server/lib/internal/modules/cjs/loader.js:1340:18) at Module.load (/home/server/lib/internal/modules/cjs/loader.js:1119:32) at Module._load (/home/server/lib/internal/modules/cjs/loader.js:960:12) at Module.require (/home/server/lib/internal/modules/cjs/loader.js:1143:19) at require (/home/server/lib/internal/modules/cjs/helpers.js:110:18) at Object.<anonymous> (/home/server/node_modules/onnxruntime-node/dist/binding.js:9:1) at Module._compile (/home/server/lib/internal/modules/cjs/loader.js:1256:14) at Module._extensions..js (/home/server/lib/internal/modules/cjs/loader.js:1310:10) at Module.load (/home/server/lib/internal/modules/cjs/loader.js:1119:32) at Module._load (node:internal/modules/cjs/loader:960:12) {code: 'ERR_DLOPEN_FAILED', stack: 'Error: Module did not self-register: '/home/r…oad (node:internal/modules/cjs/loader:960:12)', message: 'Module did not self-register: '/home/…napi-v3/linux/x64/onnxruntime_binding.node'.'}`
How to resolve this issue ?
Giving stackoverflow link post https://stackoverflow.com/q/78178187/2853298

### Reproduction

```
const TransformersApi = Function('return import("@xenova/transformers")')();
 const { CLIPVisionModelWithProjection, RawImage, AutoProcessor } = await TransformersApi;
```

**Comment by rajeshlatlong** [comment]
`const { parentPort, workerData } = require("worker_threads");
const TransformersApi = Function('return import("@xenova/transformers")')();
async function createVectors() {
  try {
    const { CLIPVisionModelWithProjection, RawImage, AutoProcessor, env } = await TransformersApi;
    const imageProcessor = await AutoProcessor.from_pretrained('Xenova/clip-vit-base-patch16');
    const visionModel = await CLIPVisionModelWithProjection.from_pretrained('Xenova/clip-vit-base-patch16');

    const { TGApiMessageList } = workerData;

    console.log("=======workerData======", workerData);

    // get image embedding:
    for (var i = 0; i < TGApiMessageList.length; i++) {
      let image = await RawImage.fromBlob(TGApiMessageList[i].imageBlob);
      let imageInputs = await imageProcessor(image);
      let { image_embeds } = await visionModel(imageInputs);
      TGApiMessageList[i]["imageEmbed"] = image_embeds.data;
      console.log('-------Vector Embeddings-------');
      console.log(TGApiMessageList[i]["imageEmbed"]);
    }

    // sending message back to the main thread
    parentPort.postMessage({ done: true, TGApiMessageList: TGApiMessageList });
  } catch (error) {
    console.log(error);
  }
}

createVectors();`
This is the complete worker file I am using to create vectors.

**Comment by JavascriptMick** [comment]
https://stackoverflow.com/questions/78178187/error-module-did-not-self-register-node-modules-onnxruntime-node-bin-napi-v3/78247951#78247951

**Comment by EMPTYVOID-DEV** [comment]
I run into the same issue when creating a pipeline inside a worker thread in Node.js.

I think the module should be exported with "NAN_MODULE_WORKER_ENABLED()" instead of "NODE_MODULE()"

[https://stackoverflow.com/questions/68598248/is-there-a-way-to-run-native-code-modules-using-worker-threads](url)

**Comment by xenova** [comment]
Hi again 👋 Does this happen with Transformers.js v3 (`npm i @huggingface/transformers`) still?

**Comment by EMPTYVOID-DEV** [comment]
Hi and yes it happens im using the latest version 3.4.0

> Hi again 👋 Does this happen with Transformers.js v3 (`npm i @huggingface/transformers`) still?

**Comment by xenova** [comment]
Thanks. cc @fs-eire if he has any ideas :)

**Comment by fs-eire** [comment]
Thank you for the info. I will try the `NAN_MODULE_WORKER_ENABLED` macro and test if it works in worker_threads.

**Comment by fs-eire** [comment]
I wrote a simple test locally like this (run a simple test in worker), but I cannot reproduce the error ( the test actually works ). Don't know which part makes the difference.

<details>
  <summary>test.ts</summary>

```ts
import { Worker, isMainThread, parentPort } from 'node:worker_threads';
import { InferenceSession, Tensor } from 'onnxruntime-common';
import { assertTensorEqual, SQUEEZENET_INPUT0_DATA, SQUEEZENET_OUTPUT0_DATA, TEST_DATA_ROOT } from '../test-utils';
import * as path from 'path';

if (isMainThread) {
  describe('E2E Tests - worker test', () => {
    it('should run in worker', (done) => {
      const worker = new Worker(__filename, {
        stdout: true,
        stderr: true,
      });
      worker.on('message', (msg) => {
        if (msg.result === 'success') {
          done();
        } else {
          done(new Error(`Worker failed: ${msg.error}`));
        }
      });
      worker.on('error', (err) => {
        console.error(`Worker error: ${err}`);
        done(err);
      });
    });
  });
} else {
  const workerMain = async () => {
    // require onnxruntime-node.
    require('../..');

    const input0 = new Tensor('float32', SQUEEZENET_INPUT0_DATA, [1, 3, 224, 224]);
    const expectedOutput0 = new Tensor('float32', SQUEEZENET_OUTPUT0_DATA, [1, 1000, 1, 1]);

    const session = await InferenceSession.create(path.join(TEST_DATA_ROOT, 'squeezenet.onnx'));

    const result = await session!.run({ data_0: input0 }, ['softmaxout_1']);
    console.log('result:', result);
    assertTensorEqual(result.softmaxout_1, expectedOutput0);
  };
  workerMain().then(
    () => {
      parentPort?.postMessage({ result: 'success' });
    },
    (err) => {
      parentPort?.postMessage({ result: 'failed', error: err });
    },
  );
}

```
</details>

**Comment by ekonoval** [comment]
I'm using Nitro and for me seems like this solved the problem, 
I had it though only with watcher and when something in the code was changed and it has to do "live rebuild".
Maybe it helps:


```
export default defineNitroConfig({
  hooks: {
    'dev:reload': () => {
      require('onnxruntime-node');
    },
  },
});
```

**Comment by fs-eire** [comment]
UPDATE:

OK I confirmed that there is an issue with ONNX Runtime Node.js binding. But it is not for supporting in worker, but for supporting for worker threads.

If the main thread and one or more worker threads loads the binding (`require('onnxruntime-node')`), the instance data will be handled incorrectly. A new PR is created to fix this issue: https://github.com/microsoft/onnxruntime/pull/24366
