### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by satyajandhyala** [xenova/transformers.js#657]
### System Info

I am using v3

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I am trying to build distribution locally using v3 branch.

> @xenova/transformers@3.0.0-alpha.0 build
> webpack && npm run typegen

assets by path dist/*.wasm 84.8 MiB
  asset dist/ort-wasm-simd-threaded.jsep.wasm 18.6 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm] [copied]
  asset dist/ort-wasm-simd.jsep.wasm 16.6 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd.jsep.wasm] [copied]
  asset dist/ort-training-wasm-simd.wasm 10.7 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-training-wasm-simd.wasm] [copied]
  asset dist/ort-wasm-simd-threaded.wasm 10.2 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm] [copied]
  asset dist/ort-wasm-simd.wasm 10.1 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm] [copied]
  asset dist/ort-wasm-threaded.wasm 9.36 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-threaded.wasm] [copied]
  asset dist/ort-wasm.wasm 9.28 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm.wasm] [copied]
assets by path dist/*.js 2.67 MiB
  asset dist/transformers.js 1.77 MiB [compared for emit] [javascript module] (name: dist/transformers) 1 related asset
  asset dist/transformers.min.js 921 KiB [compared for emit] [javascript module] [minimized] (name: dist/transformers.min) 1 related asset
runtime modules 3.54 KiB 8 modules
modules by path ./ 1.55 MiB
  modules by path ./node_modules/ 721 KiB
    modules by path ./node_modules/onnxruntime-common/dist/esm/*.js 59.4 KiB 18 modules
    + 2 modules
  modules by path ./src/ 862 KiB 18 modules
fs (ignored) 15 bytes [built] [code generated]
path (ignored) 15 bytes [built] [code generated]
url (ignored) 15 bytes [built] [code generated]
sharp (ignored) 15 bytes [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
path (ignored) 15 bytes [built] [code generated]
path (ignored) 15 bytes [built] [code generated]
onnxruntime-node (ignored) 15 bytes [built] [code generated]

ERROR in ./src/utils/dtypes.js
Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
    at C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\dependencies\HarmonyDetectionParserPlugin.js:56:11
    at Hook.eval [as call] (eval at create (C:\Users\sajandhy\transformers.js\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\sajandhy\transformers.js\node_modules\tapable\lib\Hook.js:14:14)
    at JavascriptParser.walkAwaitExpression (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2438:29)
    at JavascriptParser.walkExpression (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2368:10)
    at JavascriptParser.walkVariableDeclaration (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2222:33)
    at JavascriptParser.walkStatement (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:1633:10)
    at JavascriptParser.walkExportNamedDeclaration (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2056:9)
    at JavascriptParser.walkStatement (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:1597:10)
    at JavascriptParser.walkStatements (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:1492:9)
 @ ./src/models.js 51:0-55:27 135:35-63 136:9-52 137:82-92 138:25-40 138:45-59 143:19-47
 @ ./src/transformers.js 16:0-28 16:0-28

webpack 5.80.0 compiled with 1 error in 4236 ms

assets by path dist/*.wasm 84.8 MiB
  asset dist/ort-wasm-simd-threaded.jsep.wasm 18.6 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm] [copied]
  asset dist/ort-wasm-simd.jsep.wasm 16.6 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd.jsep.wasm] [copied]
  asset dist/ort-training-wasm-simd.wasm 10.7 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-training-wasm-simd.wasm] [copied]
  asset dist/ort-wasm-simd-threaded.wasm 10.2 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm] [copied]
  asset dist/ort-wasm-simd.wasm 10.1 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm] [copied]
  asset dist/ort-wasm-threaded.wasm 9.36 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm-threaded.wasm] [copied]
  asset dist/ort-wasm.wasm 9.28 MiB [compared for emit] [from: node_modules/onnxruntime-web/dist/ort-wasm.wasm] [copied]
assets by path dist/*.cjs 1.38 MiB
  asset dist/transformers.cjs 1.1 MiB [compared for emit] (name: dist/transformers) 1 related asset
  asset dist/transformers.min.cjs 287 KiB [compared for emit] [minimized] (name: dist/transformers.min) 1 related asset
runtime modules 3.54 KiB 8 modules
modules by path ./ 972 KiB
  modules by path ./node_modules/ 110 KiB
    ./node_modules/@huggingface/jinja/dist/index.js 50.5 KiB [built] [code generated]
    + 18 modules
  modules by path ./src/ 862 KiB 18 modules
fs (ignored) 15 bytes [built] [code generated]
path (ignored) 15 bytes [built] [code generated]
url (ignored) 15 bytes [built] [code generated]
sharp (ignored) 15 bytes [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
path (ignored) 15 bytes [built] [code generated]
path (ignored) 15 bytes [built] [code generated]
onnxruntime-node (ignored) 15 bytes [built] [code generated]
onnxruntime-web/webgpu (ignored) 15 bytes [built] [code generated]

ERROR in ./src/utils/dtypes.js
Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
    at C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\dependencies\HarmonyDetectionParserPlugin.js:56:11
    at Hook.eval [as call] (eval at create (C:\Users\sajandhy\transformers.js\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\sajandhy\transformers.js\node_modules\tapable\lib\Hook.js:14:14)
    at JavascriptParser.walkAwaitExpression (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2438:29)
    at JavascriptParser.walkExpression (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2368:10)
    at JavascriptParser.walkVariableDeclaration (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2222:33)
    at JavascriptParser.walkStatement (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:1633:10)
    at JavascriptParser.walkExportNamedDeclaration (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:2056:9)
    at JavascriptParser.walkStatement (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:1597:10)
    at JavascriptParser.walkStatements (C:\Users\sajandhy\transformers.js\node_modules\webpack\lib\javascript\JavascriptParser.js:1492:9)
 @ ./src/models.js 51:0-55:27 135:35-63 136:9-52 137:82-92 138:25-40 138:45-59 143:19-47
 @ ./src/transformers.js 16:0-28 16:0-28

webpack 5.80.0 compiled with 1 error in 2893 ms

(py38) C:\Users\sajandhy\transformers.js>

### Reproduction

Clone Ttransformers.js repo
cd transformers.js
npm i
npm run build

**Comment by xenova** [comment]
Thanks for the report. This is now fixed in https://github.com/xenova/transformers.js/pull/545/commits/aadeed936af7cc9049e1d238fd4ec70545dfd508
