### ISSUE TITLE
[Question] How to run test suit

### ISSUE THREAD

**Issue by chelouche9** [xenova/transformers.js#71]
Hi @xenova,

I want to work on adding new features, but when I try to run the tests of the project I get this error:

```
Error: File not found. Could not locate "/Users/yonatanchelouche/Desktop/passive-project/transformers.js/models/onnx/quantized/distilbert-base-uncased-finetuned-sst-2-english/sequence-classification/tokenizer.json".
    at getModelFile (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:235:23)
    at async fetchJSON (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:288:18)
    at async Promise.all (index 0)
    at async Function.from_pretrained (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/tokenizers.js:2571:48)
    at async Promise.all (index 0)
    at async pipeline (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/pipelines.js:1308:17)
    at async text_classification (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:90:22)
    at async /Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:897:25
```
I guess it is because the models are missing from the models dir. Is there a programmatic way to download them from the lib?

By the way, I was thinking about adding a CI on PRs to run the tests and perhaps adding jest as the test runner. What, do you think about that?

**Comment by xenova** [comment]
> I guess it is because the models are missing from the models dir. Is there a programmatic way to download them from the lib?

Yes that's right. Currently, I've been the only one testing the models (running them locally) because otherwise, contributors would have to download *all* the models from the hub.

If you want, you can do this by cloning the huggingface repo like this:
```bash
# Make sure you have git-lfs installed (https://git-lfs.github.com)
git lfs install
git clone https://huggingface.co/Xenova/transformers.js

# if you want to clone without large files – just their pointers
# prepend your git clone with the following env var:
GIT_LFS_SKIP_SMUDGE=1
```

> By the way, I was thinking about adding a CI on PRs to run the tests and perhaps adding jest as the test runner. What, do you think about that?

That would be AMAZING! Yes please!

**Comment by chelouche9** [comment]
I have the models and now I get another error:

```
/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:27
            this.body = new ReadableStream({
                            ^

ReferenceError: ReadableStream is not defined
    at new FileResponse (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:27:29)
    at getFile (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:177:16)
    at getModelFile (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:231:26)
    at fetchJSON (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:288:24)
    at Function.from_pretrained (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/tokenizers.js:2572:13)
    at pipeline (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/pipelines.js:1292:27)
    at text_classification (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:90:28)
    at /Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:897:31
    at Object.<anonymous> (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:903:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

Do I need to run another process except npm run test? I tried several approaches and still get this error.

**Comment by xenova** [comment]
> I have the models and now I get another error:
> 
> 
> 
> ```
> 
> /Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:27
> 
>             this.body = new ReadableStream({
> 
>                             ^
> 
> 
> 
> ReferenceError: ReadableStream is not defined
> 
>     at new FileResponse (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:27:29)
> 
>     at getFile (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:177:16)
> 
>     at getModelFile (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:231:26)
> 
>     at fetchJSON (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/utils.js:288:24)
> 
>     at Function.from_pretrained (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/tokenizers.js:2572:13)
> 
>     at pipeline (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/src/pipelines.js:1292:27)
> 
>     at text_classification (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:90:28)
> 
>     at /Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:897:31
> 
>     at Object.<anonymous> (/Users/yonatanchelouche/Desktop/passive-project/transformers.js/tests/index.js:903:3)
> 
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
> 
> ```
> 
> 
> 
> Do I need to run another process except npm run test? I tried several approaches and still get this error. It's weird because node should be available when running tests

Ah yes, there was a PR made yesterday to fix that:
- https://github.com/xenova/transformers.js/pull/72

I'll merge it soon

**Comment by xenova** [comment]
Now that automated testing is implemented (via GH actions), you probably don't need to run the test suite locally. If you would like to, feel free to follow the steps in the CI pipeline: https://github.com/xenova/transformers.js/blob/main/.github/workflows/tests.yml

Otherwise, I will close the issue.
