### ISSUE TITLE
How to choose a language's dialect when using `automatic-speech-recognition` pipeline?

### ISSUE THREAD

**Issue by jquintanilla4** [xenova/transformers.js#725]
### Question

Hi, so I was originally using the transformers library (python version) in my backend, but when refactoring my application for scale. It made more sense to move my implementation of whisper from the backend to the frontend (for my specific usecase). So I was thrilled when I saw that transformers.js supported whisper via the `automatic-speech-recognition` pipeline. However I'm a little confused by the implementation and the documentation left me with the question in the title.

How to choose a language's dialect when using `automatic-speech-recognition` pipeline?

In the python implementation of whisper, you don't have to specify the language being spoken as long as you're using the correct model size for multilingual support. But from your examples on transformers.js, it seems like you do in the js implementation.

```
const transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-small');
const url = 'https://huggingface.co/datasets/Xenova/transformers.js-docs/resolve/main/french-audio.mp3';
const output = await transcriber(url, { language: 'french', task: 'transcribe' });
// { text: " J'adore, j'aime, je n'aime pas, je déteste." }
```

However there's no list of supported languages, beyond what you can find on the whisper github repo. That's usually not a problem. But how do you deal with a language like Chinese, that has two main dialects; Mandarin and Cantonese. In python, I didn't have to worry about it, but in js, it seems to be a potential issue.

Please help. Any guidance will be appreciated.

**Comment by jquintanilla4** [comment]
I'm currently hardcoding the language for testing. But i keep getting errors when trying chinese. Here's the snippet.

```
    useEffect(() => {
        navigator.mediaDevices.getUserMedia({ audio: true })
            .then(stream => {
                const mediaRecorder = new MediaRecorder(stream);
                mediaRecorderRef.current = mediaRecorder;
                let audioChunks = [];

                mediaRecorder.ondataavailable = event => {
                    audioChunks.push(event.data);
                };

                mediaRecorder.onstop = async () => {
                    const audioBlob = new Blob(audioChunks, { type: 'audio/webm' });
                    const audioUrl = URL.createObjectURL(audioBlob);
                    audioRef.current.src = audioUrl;
                    
                    // Transcribe audio
                    try {
                        const transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-medium');
                        const result = await transcriber(audioBlob, { language: 'chinese', task: 'transcribe', chunk_length_s: 30, stride_length_s: 5 });
                        setTranscription(result.text);
                    } catch (error) {
                        console.log('Error transcribing audio:', error);
                    }

                    audioChunks = [];
                };

                audioRef.current = new Audio();
                audioRef.current.srcObject = stream;
                return () => {
                    stream.getTracks().forEach(track => track.stop());
                };
            })
            .catch(error => {
                console.log('Error accessing microphone:', error);
            });
    }, []);
```

My errors look like this:
```
ERROR
Unexpected token '<', "<!DOCTYPE "... is not valid JSON
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at getModelJSON (http://localhost:3000/main.f7a520796f16f5075263.hot-update.js:35717:15)
    at async Promise.all (index 0)
    at async loadTokenizer (http://localhost:3000/main.f7a520796f16f5075263.hot-update.js:28624:16)
    at async AutoTokenizer.from_pretrained (http://localhost:3000/main.f7a520796f16f5075263.hot-update.js:32481:46)
    at async Promise.all (index 0)
    at async loadItems (http://localhost:3000/main.f7a520796f16f5075263.hot-update.js:26511:3)
    at async pipeline (http://localhost:3000/main.f7a520796f16f5075263.hot-update.js:26456:19)
    at async mediaRecorder.onstop (http://localhost:3000/main.64a844b93bb41b13d6ab.hot-update.js:59:29)
```

I'm guessing the pipeline can't handle webm either. In python i had to convert it to .wav. Is that the same in transformers.js?

**Comment by jquintanilla4** [comment]
@xenova Thanks for the tips. It helped with loading the models and working through that problem. But now I've run into a new issue that i've tried to solve on my own, with lots of googling, LLMs, and just my knowledge of how this stuff functions in python. But I can't seem to get it to work. I keep getting this error, no matter what I do. Maybe I'm missing something obvious.

```
An error occurred during model execution: "Error: failed to call OrtRun(). error code = 6.".
Inputs given to model: {input_features: Proxy(Tensor)}

Error transcribing audio: Error: failed to call OrtRun(). error code = 6.
    at e.run (wasm-core-impl.ts:392:1)
    at e.run (proxy-wrapper.ts:212:1)
    at e.OnnxruntimeWebAssemblySessionHandler.run (session-handler.ts:99:1)
    at InferenceSession.run (inference-session-impl.ts:108:1)
    at sessionRun (models.js:207:1)
    at encoderForward (models.js:520:1)
    at Function.seq2seqForward [as _forward] (models.js:361:1)
    at Function.forward (models.js:820:1)
    at Function.seq2seqRunBeam [as _runBeam] (models.js:480:1)
    at Function.runBeam (models.js:1373:1)
```

I feel like I'm over complicating things. I'm not to good with JS, if I'm being honest, so it might be that. Here's my code for this react component:
```
import React, { useRef, useState, useEffect } from 'react';
import axios from 'axios';
import { pipeline, env } from '@xenova/transformers';
import { useTranscription } from './TranscriptionContext';


env.allowLocalModels=false;

const AudioInput = () => {
    const { addTranscription } = useTranscription();
    const [recording, setRecording] = useState(false);
    const [recordedTime, setRecordedTime] = useState(0);
    const [transcription, setTranscription] = useState('');
    const [audioUrl, setAudioUrl] = useState('');
    const audioRef = useRef(null);
    const intervalIdRef = useRef(null);
    const mediaRecorderRef = useRef(null);
    const audioChunksRef = useRef([]);
    const mimeTypeRef = useRef(null);

    useEffect(() => {
        navigator.mediaDevices.getUserMedia({ audio: true })
            .then(stream => {
                let mediaRecorder;
                let mimeType = 'audio/webm' // default MIME type

                if (MediaRecorder.isTypeSupported('audio/wav')) {
                    mimeType = 'audio/wav';
                    mediaRecorder = new MediaRecorder(stream, {
                        mimeType: mimeType,
                        audioBitsPerSecond: 16000,
                    });
                    console.log('WAV is supported. MediaRecorder initialized with WAV settings.');
                } else {
                    console.log('WAV format not supported. Falling back to default format');
                    mediaRecorder = new MediaRecorder(stream, { mimeType: mimeType });
                    console.log('MediaRecorder initialized');
                }
                mediaRecorderRef.current = mediaRecorder;
                mimeTypeRef.current = mimeType
                
                // setup event handlers
                mediaRecorder.ondataavailable = event => {
                    audioChunksRef.current.push(event.data);
                };

                mediaRecorder.onstart = () => {
                    console.log('Recording started');
                };

                mediaRecorder.onstop = async () => {
                    const audioBlob = new Blob(audioChunksRef.current, { type: mimeTypeRef.current });
                    console.log('Recording stopped. Blob created:', audioBlob);
                    console.log('Blob created with type:', mimeTypeRef.current);
                    try {
                        const audioBuffer = await blobToAudioBuffer(audioBlob);
                        const audioData = audioBufferToFloat32Array(audioBuffer);

                        // Check if audioData is a Float32Array
                        if (!(audioData instanceof Float32Array)) {
                            throw new Error('audioData is not a Float32Array');
                        }

                        // store the current URL in a local variable bfore creating a new one
                        const currentAudioUrl = audioUrl;

                        // create new URL and update state
                        const newAudioUrl = URL.createObjectURL(audioBlob); 
                        setAudioUrl(newAudioUrl); 
                        audioRef.current.src = newAudioUrl; 
                        
                        const transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-medium');
                        const result = await transcriber(audioData, { language: 'chinese', task: 'transcribe', chunk_length_s: 30, stride_length_s: 5 });
                        // console.log('Transcription', result);
                        console.log('Transcription result:', JSON.stringify(result, null, 2));
                        console.log('This is a test log immediately after transcription');
                        setTranscription(result.text);

                        // clear the audioChunksRef arrary to free up memory and prepare for new recording
                        audioChunksRef.current = [];
                        
                        // revoke the previous audio URL to free up memory
                        if (currentAudioUrl) {
                            URL.revokeObjectURL(currentAudioUrl);
                        }
                    } catch (error) {
                        console.log('Error transcribing audio:', error);
                    }
                };

                audioRef.current = new Audio(); // Create a new Audio object
                audioRef.current.srcObject = stream;
                return () => {
                    stream.getTracks().forEach(track => track.stop());
                };
            })
            .catch(error => {
                console.log('Error accessing microphone:', error);
            });
    }, [audioUrl]);


    const blobToAudioBuffer = async (blob) => {
        const audioContext = new (window.AudioContext || window.webkitAudioContext)();
        const arrayBuffer = await blob.arrayBuffer();
        const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
        return audioBuffer;
    };

    const audioBufferToFloat32Array = (audioBuffer) => {
        return audioBuffer.getChannelData(0); // mono audio; use getChannelData(1).
    };

    const startRecording = () => {
        if (mediaRecorderRef.current && mediaRecorderRef.current.state === 'inactive') {
            mediaRecorderRef.current.start();
            setRecording(true);
            intervalIdRef.current = setInterval(() => {
                setRecordedTime(prevTime => prevTime + 1);
            }, 1000);
            console.log('Recording started');
        } else {
            console.error('MediaRecorder not initialized or already recording');
        }
    };
    
    const stopRecording = () => {
        clearInterval(intervalIdRef.current);
        if (mediaRecorderRef.current && mediaRecorderRef.current.state === 'recording') {
            mediaRecorderRef.current.stop();
            console.log('Recording stopped');
        } else {
            console.error('MediaRecorder not recording or not initialized');
        }
        setRecording(false);
        setRecordedTime(0);
    };

    useEffect(() => {
        if (!recording && transcription) {
            axios.post('http://localhost:8000/upload_transcription', {transcription}) // send transcription to backend
                .then(response => {
                    console.log('Transcription sent:', response.data);
                    addTranscription(response.data); // add transcription to the context
                    setTranscription(''); // clear the transcription
                })
                .catch(error => {
                    console.log('Error sending audio and transcription:', error);
                });
        }
    }, [recording, transcription, addTranscription]);

    return (
        <div className="audio-input-container">
            <button onClick={startRecording}>Start Recording</button>
            <button onClick={stopRecording}>Stop Recording</button>
            <audio ref={audioRef} controls />
            <p>Recorded Time: {recordedTime} seconds</p>
        </div>
    );
};

export default AudioInput;
```

**Comment by dpny518** [comment]
If you don't specify the language, it defaults to english and does translation even if the task is transcribe. On python it would autodetect the language and could even do multilingual. Is there any way to have auto detect in transformers.js asr pipepline?

**Comment by serbinskis** [comment]
A year later and still the same problem, there is no way to automaticly detect language...
