### ISSUE TITLE
Where should I get `decoder_model_merged` file from?

### ISSUE THREAD

**Issue by abuchnick-aiola** [xenova/transformers.js#917]
### Question

Hey,
I'm trying to use `whisper-web` demo with my finetuned model.
After I managed connecting my model to the demo application, I'm getting errors related to this:

https://github.com/xenova/transformers.js/blob/7f5081da29c3f77ee830269ab801344776e61bcb/src/models.js#L771

Basically, when `transformers.js` tries to load a whisper model, it looks for files called `decoder_model_merged.onnx` / `decoder_model_merged_quantized.onnx` / `decoder_model_merged_fp16.onnx`.
The thing is, that the conversion script didn't create any of these files.
That's how the conversion script output looks like:
![image](https://github.com/user-attachments/assets/f6288c77-5010-4d98-a609-f38e46e1afaa)

Please help me figure out what am I missing here.
P.S. After I'll get it to work, I'll be happy to open a PR on `whisper-web` repository that will enable using local models together with remote (on HF hub) models.
Thanks !

**Comment by abuchnick-aiola** [comment]
I think it could be related to: https://github.com/xenova/whisper-web/issues/24

**Comment by xenova** [comment]
Can you try with the Transformers.js v3 conversion script?
```sh
git clone -b v3 https://github.com/xenova/transformers.js.git
cd transformers.js
pip install -q -r scripts/requirements.txt
python -m scripts.convert --quantize --model_id MODEL_ID_GOES_HERE
```

**Comment by abuchnick-aiola** [comment]
Hey @xenova,
Sure, I'll give it a try.
Thanks !

**Comment by abuchnick-aiola** [comment]
Hey @xenova and everyone else who will get here,
The problem was with how I ran the conversion script. That's how it should be done:
```
python -m scripts.convert --quantize --model_id MODEL_ID_GOES_HERE --task automatic-speech-recognition-with-past
```

**Comment by abuchnick-aiola** [comment]
Hey @xenova,
Now I'm getting: `'An error occurred during model execution: "Missing the following inputs: cache_position.'`.
What can be the issue ?

**Comment by abuchnick-aiola** [comment]
@xenova one last update (in the meantime),
By reverse engineering the `onnx-community/whisper-*` artifacts you uploaded to HF, we found out that 2 things were causing this issue:
1. Using the conversion script from `v3` branch led to the `cache_position` exception I attached above. It seems to have something to do with this being a required parameter in a higher `transformers` version (as requested in the requirements file of the conversion scripts), that `transformers.js` or `whisper-web` (on webgpu branch) code still doesn't take into consideration.
2. No matter what we tried (both development/v3 branches), `onnx` conversion of the medium or large versions of Whisper just doesn't work. It fails on the ATOL validation, no matter the atol we provided (even when 1 was provided). This happened only in the full precision (fp32), which is required in order to run `whisper-webgpu` (when we tried lower precision in the encoder, it simply didn't work).

I would love to hear any further feedback from you, as we really want to integrate `transformers.js` into our codebase, but currently the things above are blockers for us.

Thank you very much for your work !

**Comment by decoder-sh-david** [comment]
I am also curious about having more information about the conversion flow - specifically I'd like to know how the timestamped models like [this](https://huggingface.co/onnx-community/whisper-base_timestamped) where trained. 

I have also run into issues with lots of quantification variants simply not working.

**Comment by AvivSham** [comment]
> Hey @xenova, Now I'm getting: `'An error occurred during model execution: "Missing the following inputs: cache_position.'`. What can be the issue ?

@xenova 

Can you please help resolve this issue? 
For me if I try to inference the converted whisper model through python it works. however when doing the same through whisper web / transformers js I receive this error message.

The Python inference code (I just changed the model path):

```python 
from transformers import AutoProcessor, pipeline
from optimum.onnxruntime import ORTModelForSpeechSeq2Seq
from datasets import load_dataset

processor = AutoProcessor.from_pretrained("optimum/whisper-tiny.en")
model = ORTModelForSpeechSeq2Seq.from_pretrained("optimum/whisper-tiny.en")
speech_recognition = pipeline("automatic-speech-recognition", model=model, tokenizer=processor.tokenizer, feature_extractor=processor.feature_extractor)

ds = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
pred = speech_recognition(ds[0]["audio"]["array"])
```

**Comment by PierreMesure** [comment]
I just converted a fine-tuned model using the convert.py script in transformers.js-3.3.3 and I'm getting the same problem trying to load it in the whisper-webgpu webapp (using an updated transformers.js-3.3.3).

> Error: An error occurred during model execution: "Missing the following inputs: cache_position.
>     at validateInputs (models.js:374:1)
>     at sessionRun (models.js:402:1)
>     at decoderForward (models.js:584:1)
>     at Function.seq2seqForward [as _forward] (models.js:512:1)
>     at Function.forward (models.js:1137:1)
>     at Function.generate (models.js:1695:1)
>     at async Function.generate (models.js:3288:1)
>     at async Function._call_whisper (pipelines.js:1866:1)
>     at async transcribe (worker.js:136:20)

**Comment by xenova** [comment]
Apologies for the delay - this appeared to be an issue with the dependencies for certain combinations of transformers & optimum. https://github.com/huggingface/transformers.js/pull/1204 Fixes it 👍
