### ISSUE TITLE
`Xenova/multilingual-e5-large` filesystem error: in file_size: No such file or directory ["model.onnx_data"]

### ISSUE THREAD

**Issue by DavidGOrtega** [xenova/transformers.js#940]
### System Info

Node.js v18.20.3
transformers: 3.0.0-alpha.15

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

This model works in v2.17.2 however in v3 fails.

```
2024-09-21 11:16:10.203 node[41824:5940827] 2024-09-21 11:16:10.203486 [E:onnxruntime:, inference_session.cc:2105 operator()] Exception during initialization: filesystem error: in file_size: No such file or directory ["model.onnx_data"]
/***/node_modules/@huggingface/transformers/node_modules/onnxruntime-node/dist/backend.js:27
            __classPrivateFieldGet(this, _OnnxruntimeSessionHandler_inferenceSession, "f").loadModel(pathOrBuffer.buffer, pathOrBuffer.byteOffset, pathOrBuffer.byteLength, options);
                                                                                           ^

Error: Exception during initialization: filesystem error: in file_size: No such file or directory ["model.onnx_data"]
    at new OnnxruntimeSessionHandler (/***/packages/conjurors/node_modules/@huggingface/transformers/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at Immediate.<anonymous> (/***/node_modules/@huggingface/transformers/node_modules/onnxruntime-node/dist/backend.js:64:29)
    at process.processImmediate (node:internal/timers:476:21)
```

### Reproduction

```js
import { pipeline } from '@huggingface/transformers';

const run = async () => {
  // const model = 'onnx-community/gte-multilingual-base';
  // const model = 'Xenova/multilingual-e5-base';
  const model = 'Xenova/multilingual-e5-large';
  const extractor = await pipeline('feature-extraction', model, { pooling: 'mean', normalize: true });

  const texts = ['Hello world.', 'Example sentence.'];
  const embeddings = await extractor(texts );
  console.log(embeddings, model);
}

run();
```

**Comment by xenova** [comment]
Hi again 👋 This is the same issue as https://github.com/xenova/transformers.js/issues/938#issuecomment-2365400427.

**Comment by xenova** [comment]
https://github.com/huggingface/transformers.js/issues/938#issuecomment-2901959919
