### ISSUE TITLE
Pipeline tries to download all the possible weights even when the dtype is specified: utils/hub.js could not locate file

### ISSUE THREAD

**Issue by DavidGOrtega** [xenova/transformers.js#941]
### System Info

tranformers v2.17.2
node v18.20.3

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

For some reason, [specifying the `dtype`](https://github.com/xenova/transformers.js/issues/676) is still downloading all the other weights. This approach has some issues: 
 - Is a waste of space and bandwidth (specially HF)
 - Prevents you to use other repos that has not converted the models to other dtypes  [like this one](https://huggingface.co/intfloat/multilingual-e5-large/tree/main/onnx)
 

```
file:///***/node_modules/@xenova/transformers/src/utils/hub.js:238
    throw Error(`${message}: "${remoteURL}".`);
          ^

Error: Could not locate file: "https://huggingface.co/intfloat/multilingual-e5-large/resolve/main/onnx/model_quantized.onnx".
    at handleError (file:///***/node_modules/@xenova/transformers/src/utils/hub.js:238:11)
    at getModelFile (file:///***/node_modules/@xenova/transformers/src/utils/hub.js:471:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async constructSession (file:///***/node_modules/@xenova/transformers/src/models.js:123:18)
    at async Promise.all (index 1)
    at async XLMRobertaModel.from_pretrained (file:///***/node_modules/@xenova/transformers/src/models.js:793:20)
    at async AutoModel.from_pretrained (file:///***/node_modules/@xenova/transformers/src/models.js:5519:20)
    at async Promise.all (index 1)
    at async loadItems (file:///***/node_modules/@xenova/transformers/src/pipelines.js:3279:5)
    at async pipeline (file:///***/node_modules/@xenova/transformers/src/pipelines.js:3219:21)
```

### Reproduction

```js

import { pipeline, env } from '@xenova/transformers';

const run = async () => {
  const model = 'intfloat/multilingual-e5-large';
  const extractor = await pipeline('feature-extraction', model, { pooling: 'mean', normalize: true,  dtype: 'fp32' });

  const texts = ['Hello world.', 'Example sentence.'];
  const embeddings = await extractor(texts);
  console.log(embeddings, model);
}

run();

**Comment by xenova** [comment]
Hi there 👋 Please note that the `dtype` option is only available in `@huggingface/transformers` (Transformers.js v3) instead of `@xenova/transformers`.

**Comment by tarikakyol** [comment]
thanks for the hard work!, I've spent some days until I figured out there's a newer version of transformers.js at @huggingface/transformers, it might just be me being slow but I think this should be a bit more explicit.
